import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home({ users }) {
   console.log(
      users.map((item) => item.title),
      "==>  get static props users"
   );
   return (
      <div className={styles.container}>
         <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <main className={styles.main}>
            <ul>
               <li>
                  <Link href='/courses'> go to courses</Link>
               </li>
               <li>
                  <Link href='/articles' replace>
                     articles
                  </Link>
               </li>
            </ul>
         </main>

         <section>
            <ul>
               {users.map((item) => (
                  <li key={item.id}>
                     <p>{item.name}</p>
                  </li>
               ))}
            </ul>
         </section>ّ

         <footer className={styles.footer}>
            <span className={styles.logo}>
               <Image
                  src='/vercel.svg'
                  alt='Vercel Logo'
                  width={72}
                  height={16}
               />
            </span>
         </footer>
      </div>
   );
}

export async function getStaticProps() {
   const data = "nstrn prshrf";
   const res = await fetch("https://jsonplaceholder.typicode.com/users");
   const users = await res.json();

   return {
      props: { users },
   };
}
