import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
   return (
      <div className={styles.container}>
         <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <main className={styles.main}>
            <ul>
               <li>
                  <Link href='/courses'> go to courses</Link>
               </li>
               <li>
                  <Link href='/articles' replace>articles</Link>
               </li>
            </ul>
         </main>

         <footer className={styles.footer}>
            <span className={styles.logo}>
               <Image
                  src='/vercel.svg'
                  alt='Vercel Logo'
                  width={72}
                  height={16}
               />
            </span>
         </footer>
      </div>
   );
}
